spring:
  thymeleaf:
    cache: false

  redis:
    host: localhost
    port: 6379
    database: 0
    #超时时间 
    timeout: 10000ms
    lettuce:
      pool:
        #最大连接数量
        max-active: 8
        #最大连接阻塞等待时间
        max-wait: 10000
        #最大空闲连接，默认8
        max-idle: 200
        #最小空闲连接，默认0
        min-idle: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: w.1998
    hikari:
      pool-name: DateHikariCP
      #???????
      minimum-idle: 5
      #??????????????????600000?
      idle-timeout: 18000000
      #?????????10
      maximum-pool-size: 10
      #?????????????
      auto-commit: true
      #?????????0?????????1800000?30???
      max-lifetime: 1800000
      #?????????30?
      connection-timeout: 30000
      #?????????????
      connection-test-query: select 1
  rabbitmq:
    #服务器
    host: localhost
    #用户名
    username: guest
    #密码
    password: guest
    #虚拟主机
    virtual-host: /
    #端口
    port: 5672
    listener:
      simple:
        #消费者最小数量
        concurrency: 10
        #消费者最大数量
        max-concurrency: 10
        #限制消费者每次只处理一条消息，处理完再继续下一条消息
        prefetch: 1
        #启动时是否默认启动容器，默认ture
        auto-startup: true
        #消息被拒绝时候重新进入队列
        default-requeue-rejected: true
    template:
      retry:
        #发布重试，默认false
        enabled: true
        #重试时间，默认为1000ms
        initial-interval: 1000ms
        #重试最大次数，默认为3
        max-attempts: 3
        #重试最大间隔时间，默认为10000ms
        max-interval: 10000ms
        #重试间隔乘数，比如配2.0，第二次就是20s,第三次就是40s
        multiplier: 1

mybatis-plus:
  #mapper????
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #??mybatis???????????????
  type-aliases-package:

logging:
  level:
    #???????????xml??????
    com.wang.seckillrabbit.mapper: debug