spring:
  thymeleaf:
    cache: false

  redis:
    host: localhost
    port: 6379
    database: 0
    #超时时间 
    timeout: 10000ms
    lettuce:
      pool:
        #最大连接数量
        max-active: 8
        #最大连接阻塞等待时间
        max-wait: 10000
        #最大空闲连接，默认8
        max-idle: 200
        #最小空闲连接，默认0
        min-idle: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: w.1998
    hikari:
      pool-name: DateHikariCP
      #???????
      minimum-idle: 5
      #??????????????????600000?
      idle-timeout: 18000000
      #?????????10
      maximum-pool-size: 10
      #?????????????
      auto-commit: true
      #?????????0?????????1800000?30???
      max-lifetime: 1800000
      #?????????30?
      connection-timeout: 30000
      #?????????????
      connection-test-query: select 1

mybatis-plus:
  #mapper????
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #??mybatis???????????????
  type-aliases-package:

logging:
  level:
    #???????????xml??????
    com.wang.seckillrabbit.mapper: debug